export const openApiInfoDescription = [
  "Normal's public REST API for one User's server-side personal automations.",
  "",
  "## Getting started",
  "",
  "Create an API Key from the signed-in dashboard at `/dashboard/api-keys`. Choose a unique name, any non-empty subset of the four permissions, the WhatsApp Connections this automation may use, and an optional expiry. The plaintext credential is shown once. If that response is lost, create a replacement key.",
  "",
  "Call `https://api.normal.fast` from a server. Do not put an API Key in a browser, mobile app, query parameter, cookie, or this documentation site.",
  "",
  "```bash",
  "curl -sS https://api.normal.fast/v1/connections \\",
  "  -H 'Authorization: Bearer <API Key>'",
  "```",
  "",
  "Signed-in API Key management routes (`/v1/api-keys`) are product routes. They require a Clerk bearer token, the exact web Origin, and — for creation — first-factor verification within five minutes. They are not authenticated with an API Key.",
  "",
  "## Server-side authentication",
  "",
  "Send one `Authorization: Bearer <API Key>` header. The credential uses the `normal_apk_` split format: a public `apk_` handle and a high-entropy secret shown only at creation. Duplicate or oversized authorization headers are rejected.",
  "",
  "Neon is the sole authority for validity, selected Connections, permissions, expiry, and revocation. There is no cache that can extend a revoked or expired key. Invalid, malformed, expired, or revoked credentials return the same 401 Problem Details shape.",
  "",
  "## Permissions",
  "",
  "| Permission | Capabilities |",
  "| --- | --- |",
  "| `connections:read` | List WhatsApp Connections explicitly selected for this API Key. |",
  "| `directory:read` | Page Directory contacts and currently joined groups. |",
  "| `messages:read` | Page WhatsApp Conversations, complete Stored Messages, private exact-word search, and eligible Stored Media. |",
  "| `messages:send` | Create or replay text Send Operations. |",
  "",
  "Permissions are independent. `messages:send` never implies Directory or Stored Message read permission. A newly created WhatsApp Connection is never added to an existing API Key.",
  "",
  "## Pagination",
  "",
  "Collection responses use `data`, `pagination`, and optional `meta`. `pagination` contains `next_cursor` and `has_more`. The default page size is 20 and the maximum is 50, except Stored Message search which remains capped at 20.",
  "",
  "REST cursors are short-lived HMAC keyset cursors bound to the calling API Key, operation, WhatsApp Connection, normalized filters or a keyed digest of search terms, limit, sort version, and a 15-minute expiry. MCP cursors are not accepted. A tampered, expired, or rebound cursor returns 400. Search terms themselves never appear in a cursor.",
  "",
  "## Problem Details",
  "",
  "REST errors use RFC 9457 `application/problem+json` with `type`, `title`, `status`, a safe `detail`, a stable Normal `code`, and optional `retryable`, `retry_after_seconds`, or `resets_at`.",
  "",
  "| Code | Status | Meaning |",
  "| --- | --- | --- |",
  "| `invalid_credentials` | 401 | Missing, malformed, expired, or revoked API Key. |",
  "| `insufficient_permission` | 403 | The grant does not include the required permission. |",
  "| `not_found` | 404 | Unknown, cross-tenant, deleted, excluded, or mismatched resource. The shape is constant. |",
  "| `invalid_request` / `invalid_cursor` | 400 | Closed request, header, or cursor contract failed. |",
  "| `idempotency_conflict` / `connection_unavailable` | 409 | Idempotency payload mismatch, or the Connection is not connected for a new send. |",
  "| `rate_limited` | 429 | Personal Account or API Key quota is exhausted. |",
  "| `unavailable` | 503 | Authentication, audit, or quota authority is unavailable. The request fails closed. |",
  "",
  "Each `type` is `https://docs.normal.fast/problems/{code}`.",
  "",
  "## Idempotency",
  "",
  "`POST /v1/connections/{connection_id}/send-operations` requires `Idempotency-Key` using the NanoID default alphabet (21 characters). Exact replay returns the existing Send Operation without calling the provider again or consuming send quota. A changed payload under the same key returns `idempotency_conflict`.",
  "",
  "## Ambiguous sends",
  "",
  "A Send Operation is not a Stored Message. After the durable provider-attempt boundary, `failed` and `unknown` remain Send Operation resources, not HTTP execution errors. An unknown outcome means the provider may have accepted the message. Normal never automatically retries an unknown Send Operation.",
  "",
  "## Retention and history coverage",
  "",
  "Stored Messages, Stored Media, and Pending Send Content follow the User's Message Retention Policy. The default is 30 days. Pending Send Content also expires at most seven days after Send Operation creation.",
  "",
  "Message pages include the Message History Window (`history_starts_at`, `history_start_reason`) and intersecting Ingestion Gaps. History is observed, not provider-certified complete. The absence of a known gap does not prove that every provider message arrived.",
  "",
  "Disconnected WhatsApp Connections remain readable for retained history. New Send Operations require a connected Connection.",
  "",
  "## Media",
  "",
  "Eligible Stored Media appears as an authenticated nested path on the Stored Message, never an MCP URI, public URL, provider URL, R2 URL, or presigned URL. `GET` that path with the same API Key. v1 returns the complete ready object up to 16 MiB after Activity Log admission and full-byte quota reservation. Responses use the normalized MIME type, a sanitized optional filename, and `Cache-Control: private, no-store`. Range and chunk downloads are not provided.",
  "",
  "Unknown, mismatched, excluded, non-ready, unauthorized, or oversized media share one constant-shape 404.",
  "",
  "## Deletion",
  "",
  "Connection Deletion immediately removes that WhatsApp Connection from every API Key. If it was a key's last selected Connection, the key is revoked and its digest is cleared. Personal Account Deletion revokes every API Key and clears every digest before purge continues. Safe expired or revoked metadata remains visible in the dashboard for 90 days, then purges. Activity Logs retain their own 90-day window.",
  "",
  "WhatsApp Recipient Exclusions apply beneath every API Key. Excluded recipients are absent from Directory, conversation, message, and media results. A send to an excluded recipient returns the same 404 as an unknown recipient. Removing an exclusion never restores purged history.",
  "",
  "## Restore invalidation",
  "",
  "A production database restore globally invalidates every restored API Key before verification traffic reopens. Digests are cleared and the API Key HMAC authority is rotated. Previous HMAC generations are not accepted as a fallback. Users create replacement keys after recovery.",
  "",
  "## Privacy",
  "",
  "Do not send raw phone numbers, provider identifiers, or self-attested confirmation flags. Public fields use opaque handles (`con_`, `ctc_`, `grp_`, `cvs_`, `msg_`, `med_`, `snd_`, `apk_`) and suffix-only phone presentation.",
  "",
  "Search terms, message content, media bytes, credentials, credential digests, full phone numbers, provider payloads, raw bodies, and tenant identifiers must not appear in URLs, cursors, Activity Logs, telemetry, or Problem Details. `POST /v1/connections/{connection_id}/messages/search` accepts terms only in a closed JSON body and binds pagination to a keyed digest of the normalized terms.",
  "",
  "This documentation site cannot execute authenticated requests or persist an API Key. Server-side curl and language examples are generated for copy-out use only.",
].join("\n");
